package com.buyeong.umji.api.model

import com.buyeong.umji.api.enums.StaffStatusEnum
import java.time.LocalDateTime

data class StaffModel(
    val id: Int,
    val status: StaffStatusEnum,
    val recruitStatus: String?,
    val lastname: String,
    val firstname: String?,
    val middlename: String?,
    val nickname: String?,
    val nationalId: String?,
    val image: String?,
    val open: Boolean,
    val openOrder: Short?,
    val openGroup: Char?,
    val email: String?,
    val homePhone: String?,
    val handPhone: String?,
    val birthdate: String?,
    val gender: String,
    val nationality: String?,
    val loginId: String?,
    val married: Boolean?,
    val birthPlace: String?,
    val homepage: String?,
    val inKorea: String?,
    val educationLevel: String?,
    val note: String?,
    val teacher: Boolean?,
    val onlineTeacherOnly: Boolean?,
    val wmSupervisor: Boolean?,
    val onlineTimeType: String?,
    val ibtTimeType: String?,
    val rcContactPoint: Boolean?,
    val branchId: Int?,
    val orgAppId: Int?,
    val tempType: String?,
    val eipEmployeeId: String?,
    val noneCdi: Boolean?,
    val noneCdiCode: Int?,
    val supervisor: Boolean?,
    val manager: Boolean?,
    val unrestAccess: Boolean?,
    var passwordChangeDate: LocalDateTime?,
    val freelancer: Boolean?,
    val admin: Boolean?,
    val studentId: Int?,
    val callingNumber: String?,
    val workType: String? = null,
)