package com.buyeong.umji.api.dto

import com.buyeong.umji.api.enums.StaffStatusEnum
import java.time.LocalDateTime

data class StaffDto(
    val id: Int = 0,
    val status: StaffStatusEnum,
    val recruitStatus: String?,
    val lastname: String,
    val firstname: String?,
    val middlename: String?,
    val nickname: String?,
    val nationalId: String?,
    val image: String?,
    val open: Boolean,
    val openOrder: Short?,
    val openGroup: String?,
    val email: String?,
    val homePhone: String?,
    val handPhone: String?,
    val birthdate: String?,
    val gender: String,
    val nationality: String?,
    val bankAccount: String?,
    val bank: String?,
    val loginId: String?,
    val password: String?,
    val married: Boolean?,
    val birthPlace: String?,
    val homepage: String?,
    val inKorea: String?,
    val educationLevel: String?,
    val note: String?,
    val teacher: Boolean?,
    val onlineTeacherOnly: Boolean?,
    val wmSupervisor: Boolean?,
    val onlineTimeType: String?,
    val ibtTimeType: String?,
    val rcContactPoint: Boolean?,
    val createdBy: Int,
    val createdAt: LocalDateTime? = null,
    val updatedBy: Int,
    val updatedAt: LocalDateTime? = null,
    val branchId: Int?,
    val orgAppId: Int?,
    val newLogin: String?,
    val loginBackup: String?,
    val tempType: String?,
    val eipEmployeeId: String?,
    val noneCdi: Boolean?,
    val noneCdiCode: Int?,
    val supervisor: Boolean?,
    val manager: Boolean?,
    val unrestAccess: Boolean?,
    var passwordEncryption: String?,
    var passwordChangeDate: LocalDateTime?,
    val freelancer: Boolean?,
    val admin: Boolean?,
    val webLoginId: String?,
    val studentId: Int?,
    val callingNumber: String?,
    val allimPushId: Int?,
    val samsLoginId: String?,
    val workType: String?,
)