CREATE TABLE purchase_order_tax_invoice (
    order_id BIGINT PRIMARY KEY,
    status VARCHAR(30) NOT NULL,
    written_date DATE NULL,
    supply_date DATE NULL,
    supplier_registration_number VARCHAR(30) NULL,
    supplier_business_name VARCHAR(200) NULL,
    supplier_name VARCHAR(100) NULL,
    supplier_address VARCHAR(500) NULL,
    supplier_industry VARCHAR(100) NULL,
    supplier_item VARCHAR(100) NULL,
    supplier_email VARCHAR(255) NULL,
    buyer_registration_number VARCHAR(30) NULL,
    buyer_business_name VARCHAR(200) NULL,
    buyer_name VARCHAR(100) NULL,
    buyer_postal_code VARCHAR(20) NULL,
    buyer_address1 VARCHAR(255) NULL,
    buyer_address2 VARCHAR(255) NULL,
    buyer_industry VARCHAR(100) NULL,
    buyer_item VARCHAR(100) NULL,
    buyer_email VARCHAR(255) NULL,
    CONSTRAINT FK_purchase_order_tax_invoice_order FOREIGN KEY (order_id) REFERENCES purchase_order(id),
    CONSTRAINT CK_purchase_order_tax_invoice_status CHECK (status IN ('LEGACY', 'WAITING_FOR_SHIPMENT', 'READY_FOR_ISSUANCE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO purchase_order_tax_invoice (
    order_id,
    status,
    written_date,
    supply_date,
    supplier_registration_number,
    supplier_business_name,
    supplier_name,
    supplier_address,
    supplier_industry,
    supplier_item,
    supplier_email,
    buyer_registration_number,
    buyer_business_name,
    buyer_name,
    buyer_postal_code,
    buyer_address1,
    buyer_address2,
    buyer_industry,
    buyer_item,
    buyer_email
)
SELECT id,
       COALESCE(tax_invoice_status, 'LEGACY'),
       tax_invoice_written_date,
       tax_invoice_supply_date,
       tax_invoice_supplier_registration_number,
       tax_invoice_supplier_business_name,
       tax_invoice_supplier_name,
       tax_invoice_supplier_address,
       tax_invoice_supplier_industry,
       tax_invoice_supplier_item,
       tax_invoice_supplier_email,
       tax_invoice_buyer_registration_number,
       tax_invoice_buyer_business_name,
       tax_invoice_buyer_name,
       tax_invoice_buyer_postal_code,
       tax_invoice_buyer_address1,
       tax_invoice_buyer_address2,
       tax_invoice_buyer_industry,
       tax_invoice_buyer_item,
       tax_invoice_buyer_email
FROM purchase_order
WHERE tax_invoice_requested = TRUE;

ALTER TABLE purchase_order
    DROP CHECK CK_purchase_order_tax_invoice_status,
    DROP COLUMN tax_invoice_requested,
    DROP COLUMN tax_invoice_status,
    DROP COLUMN tax_invoice_written_date,
    DROP COLUMN tax_invoice_supply_date,
    DROP COLUMN tax_invoice_supplier_registration_number,
    DROP COLUMN tax_invoice_supplier_business_name,
    DROP COLUMN tax_invoice_supplier_name,
    DROP COLUMN tax_invoice_supplier_address,
    DROP COLUMN tax_invoice_supplier_industry,
    DROP COLUMN tax_invoice_supplier_item,
    DROP COLUMN tax_invoice_supplier_email,
    DROP COLUMN tax_invoice_buyer_registration_number,
    DROP COLUMN tax_invoice_buyer_business_name,
    DROP COLUMN tax_invoice_buyer_name,
    DROP COLUMN tax_invoice_buyer_postal_code,
    DROP COLUMN tax_invoice_buyer_address1,
    DROP COLUMN tax_invoice_buyer_address2,
    DROP COLUMN tax_invoice_buyer_industry,
    DROP COLUMN tax_invoice_buyer_item,
    DROP COLUMN tax_invoice_buyer_email;
