ALTER TABLE file_asset
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0 AFTER uploaded_at,
    ADD COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) AFTER created_at;
